//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alien_Isolation_Mod_Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alien_Isolation_Mod_Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _DIRECTORY_CONTENTS {
            get {
                object obj = ResourceManager.GetObject("_DIRECTORY_CONTENTS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ACID_BURST_LARGE {
            get {
                object obj = ResourceManager.GetObject("ACID_BURST_LARGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ACID_BURST_SMALL {
            get {
                object obj = ResourceManager.GetObject("ACID_BURST_SMALL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AIRPORT_NPC_B_W {
            get {
                object obj = ResourceManager.GetObject("AIRPORT_NPC_B+W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ALIEN {
            get {
                object obj = ResourceManager.GetObject("ALIEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ALIEN_DOORWAY {
            get {
                object obj = ResourceManager.GetObject("ALIEN_DOORWAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alien_Middle {
            get {
                object obj = ResourceManager.GetObject("Alien_Middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alien_RightOfScreen {
            get {
                object obj = ResourceManager.GetObject("Alien_RightOfScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ALIENCONFIGS {
            get {
                object obj = ResourceManager.GetObject("ALIENCONFIGS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AMMOTYPES {
            get {
                object obj = ResourceManager.GetObject("AMMOTYPES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ANDROID {
            get {
                object obj = ResourceManager.GetObject("ANDROID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANDROID_ALERT {
            get {
                object obj = ResourceManager.GetObject("ANDROID_ALERT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANDROID_DOORWAY {
            get {
                object obj = ResourceManager.GetObject("ANDROID_DOORWAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ANDROID_HEAVY {
            get {
                object obj = ResourceManager.GetObject("ANDROID_HEAVY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ATTRIBUTES {
            get {
                object obj = ResourceManager.GetObject("ATTRIBUTES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AXEL {
            get {
                object obj = ResourceManager.GetObject("AXEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACKSTAGEALERT {
            get {
                object obj = ResourceManager.GetObject("BACKSTAGEALERT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACKSTAGEHOLD {
            get {
                object obj = ResourceManager.GetObject("BACKSTAGEHOLD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACKSTAGEHOLD_MILD {
            get {
                object obj = ResourceManager.GetObject("BACKSTAGEHOLD_MILD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACKSTAGEHOLD_VCLOSE {
            get {
                object obj = ResourceManager.GetObject("BACKSTAGEHOLD_VCLOSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BACSTAGEHOLD_CLOSE {
            get {
                object obj = ResourceManager.GetObject("BACSTAGEHOLD_CLOSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BASE_HUMAN {
            get {
                object obj = ResourceManager.GetObject("BASE_HUMAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BOLTGUN_NORMAL {
            get {
                object obj = ResourceManager.GetObject("BOLTGUN_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Brainiac_Design {
            get {
                object obj = ResourceManager.GetObject("Brainiac_Design", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Brainiac_Designer {
            get {
                object obj = ResourceManager.GetObject("Brainiac_Designer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CANTEEN {
            get {
                object obj = ResourceManager.GetObject("CANTEEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CATALYST_FIRE_LARGE {
            get {
                object obj = ResourceManager.GetObject("CATALYST_FIRE_LARGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CATALYST_FIRE_SMALL {
            get {
                object obj = ResourceManager.GetObject("CATALYST_FIRE_SMALL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CATALYST_HE_LARGE {
            get {
                object obj = ResourceManager.GetObject("CATALYST_HE_LARGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CATALYST_HE_SMALL {
            get {
                object obj = ResourceManager.GetObject("CATALYST_HE_SMALL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CATTLEPROD_POWERPACK {
            get {
                object obj = ResourceManager.GetObject("CATTLEPROD_POWERPACK", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CIVILIAN {
            get {
                object obj = ResourceManager.GetObject("CIVILIAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CONNOR {
            get {
                object obj = ResourceManager.GetObject("CONNOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CREWEXPENDABLE_VENT {
            get {
                object obj = ResourceManager.GetObject("CREWEXPENDABLE_VENT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CUTSCENE {
            get {
                object obj = ResourceManager.GetObject("CUTSCENE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CUTSCENE_ANDROID {
            get {
                object obj = ResourceManager.GetObject("CUTSCENE_ANDROID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;workspaces selected=&quot;Alien Isolation Workspace&quot;&gt;
        ///  &lt;workspace name=&quot;Alien Isolation Workspace&quot; folder=&quot;BEHAVIOUR_TREES&quot; export=&quot;BEHAVIOUR_TREES&quot;&gt;
        ///    &lt;plugin&gt;LegendPlugin.dll&lt;/plugin&gt;
        ///  &lt;/workspace&gt;
        ///&lt;/workspaces&gt;.
        /// </summary>
        internal static string debug_workspaces {
            get {
                return ResourceManager.GetString("debug_workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DEFAULT {
            get {
                object obj = ResourceManager.GetObject("DEFAULT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DEFAULTS {
            get {
                object obj = ResourceManager.GetObject("DEFAULTS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DIFFICULTYSETTINGS {
            get {
                object obj = ResourceManager.GetObject("DIFFICULTYSETTINGS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EASY {
            get {
                object obj = ResourceManager.GetObject("EASY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMP_BURST_LARGE {
            get {
                object obj = ResourceManager.GetObject("EMP_BURST_LARGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMP_BURST_LARGE_TIER2 {
            get {
                object obj = ResourceManager.GetObject("EMP_BURST_LARGE_TIER2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMP_BURST_LARGE_TIER3 {
            get {
                object obj = ResourceManager.GetObject("EMP_BURST_LARGE_TIER3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EMP_BURST_SMALL {
            get {
                object obj = ResourceManager.GetObject("EMP_BURST_SMALL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!-- Defines the hierarchical settings exposed by the engine --&gt;
        ///&lt;Settings&gt;
        ///	&lt;Setting name=&quot;Graphics&quot;&gt;
        ///		&lt;Setting name=&quot;Stereo Mode&quot;&gt;
        ///			&lt;Quality name=&quot;Off&quot;  				precedence=&quot;4&quot;/&gt;
        ///		&lt;/Setting&gt;
        ///		&lt;Setting name=&quot;Depth of Field&quot;&gt;
        ///			&lt;Quality name=&quot;On&quot;		  	bool=&quot;1&quot;		precedence=&quot;2&quot;&gt;
        ///				&lt;DefaultRequirements&gt;
        ///					&lt;WindowsExperienceIndex type=&quot;GPU&quot; value=&quot;5.0&quot;/&gt;
        ///				&lt;/DefaultRequirements&gt;
        ///			&lt;/Quality&gt;
        ///			&lt;Quality name=&quot;Off&quot; 		bool=&quot;0&quot;		preced [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENGINE_SETTINGS {
            get {
                return ResourceManager.GetString("ENGINE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ENVIRONMENT_FLAME {
            get {
                object obj = ResourceManager.GetObject("ENVIRONMENT_FLAME", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FACEHUGGER {
            get {
                object obj = ResourceManager.GetObject("FACEHUGGER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FLAMETHROWER_AERATED {
            get {
                object obj = ResourceManager.GetObject("FLAMETHROWER_AERATED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FLAMETHROWER_HIGH_DAMAGE {
            get {
                object obj = ResourceManager.GetObject("FLAMETHROWER_HIGH_DAMAGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FLAMETHROWER_NORMAL {
            get {
                object obj = ResourceManager.GetObject("FLAMETHROWER_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gamelogo {
            get {
                object obj = ResourceManager.GetObject("gamelogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GBL_ITEM {
            get {
                object obj = ResourceManager.GetObject("GBL_ITEM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;item_database xmlns=&quot;http://www.w3schools.com&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.w3schools.com gbl_item.xsd&quot;&gt;
        ///  &lt;special_slots&gt;
        ///    &lt;slot name=&quot;SHOTGUN_WEAPON_SLOT&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;3&quot; height=&quot;2&quot; /&gt;
        ///    &lt;slot name=&quot;PISTOL_WEAPON_SLOT&quot; x=&quot;3&quot; y=&quot;0&quot; width=&quot;2&quot; height=&quot;1&quot; /&gt;
        ///    &lt;slot name=&quot;MELEE_WEAPON&quot; x=&quot;3&quot; y=&quot;1&quot; width=&quot;2&quot; height=&quot;1&quot; /&gt;
        ///	&lt;slot name=&quot;CATTLEPROD_SLOT&quot; x=&quot;0&quot; y=&quot;0&quot; width=&quot;3&quot; height=&quot;1&quot; /&gt;
        ///    &lt;slot name=&quot;FLAME_THROWER_WEAPON_SLOT&quot; x=&quot;0&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GBL_ITEM1 {
            get {
                return ResourceManager.GetString("GBL_ITEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_FIRE {
            get {
                object obj = ResourceManager.GetObject("GRENADE_FIRE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_FIRE_TIER2 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_FIRE_TIER2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_FIRE_TIER3 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_FIRE_TIER3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_HE {
            get {
                object obj = ResourceManager.GetObject("GRENADE_HE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_HE_TIER2 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_HE_TIER2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_HE_TIER3 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_HE_TIER3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_SMOKE {
            get {
                object obj = ResourceManager.GetObject("GRENADE_SMOKE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_STUN {
            get {
                object obj = ResourceManager.GetObject("GRENADE_STUN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_STUN_TIER2 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_STUN_TIER2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRENADE_STUN_TIER3 {
            get {
                object obj = ResourceManager.GetObject("GRENADE_STUN_TIER3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alpha_threshold=0.026667
        ///primary_spec_level=0.068333
        ///secondary_spec_level=1.0
        ///primary_spec_width=2.2
        ///secondary_spec_width=7.86667
        ///spec_separation=1.28333
        ///glint_intensity=0.0
        ///glint_width=0.233333
        ///diffuse_level=2.0
        ///base_absorption=1.24
        ///absorption_rate=1.50667
        ///ao_absorption=0.766667
        ///scatter_dist_rate=2.0
        ///occlusion_rate=13.35
        ///occlusion_bias=0.526667
        ///occlusion_ao_infl=0.84
        ///specular_occlusion=4.8
        ///specular_ao=6.3
        ///sub_strand_frequency=17.26
        ///sub_strand_spec_shift=0.055
        ///softening_length=0.0109
        ///so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HAIR_SHADING_SETTINGS {
            get {
                return ResourceManager.GetString("HAIR_SHADING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HARD {
            get {
                object obj = ResourceManager.GetObject("HARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IMPACT {
            get {
                object obj = ResourceManager.GetObject("IMPACT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] INNOCENT {
            get {
                object obj = ResourceManager.GetObject("INNOCENT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] INTENSE {
            get {
                object obj = ResourceManager.GetObject("INTENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IRON {
            get {
                object obj = ResourceManager.GetObject("IRON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Isolation_Isolation {
            get {
                object obj = ResourceManager.GetObject("Isolation_Isolation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] JixellationBold_Jixellation {
            get {
                object obj = ResourceManager.GetObject("JixellationBold_Jixellation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KUHLMAN_DEATH {
            get {
                object obj = ResourceManager.GetObject("KUHLMAN_DEATH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KUHLMAN_DEATH1 {
            get {
                object obj = ResourceManager.GetObject("KUHLMAN_DEATH1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LegendPlugin {
            get {
                object obj = ResourceManager.GetObject("LegendPlugin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MEDIUM {
            get {
                object obj = ResourceManager.GetObject("MEDIUM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MELEE_CROW_AXE {
            get {
                object obj = ResourceManager.GetObject("MELEE_CROW_AXE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MELEE_HUMAN {
            get {
                object obj = ResourceManager.GetObject("MELEE_HUMAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MILD {
            get {
                object obj = ResourceManager.GetObject("MILD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MODERATE {
            get {
                object obj = ResourceManager.GetObject("MODERATE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MODERATELY_INTENSE {
            get {
                object obj = ResourceManager.GetObject("MODERATELY_INTENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NostromoBoldCond_Nostromo_Cond {
            get {
                object obj = ResourceManager.GetObject("NostromoBoldCond_Nostromo_Cond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NOVICE {
            get {
                object obj = ResourceManager.GetObject("NOVICE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NPC_DOOR {
            get {
                object obj = ResourceManager.GetObject("NPC_DOOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PISTOL_DUM_DUM {
            get {
                object obj = ResourceManager.GetObject("PISTOL_DUM_DUM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PISTOL_NORMAL {
            get {
                object obj = ResourceManager.GetObject("PISTOL_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PISTOL_NORMAL_NPC {
            get {
                object obj = ResourceManager.GetObject("PISTOL_NORMAL_NPC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PISTOL_TAZER {
            get {
                object obj = ResourceManager.GetObject("PISTOL_TAZER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PUSH {
            get {
                object obj = ResourceManager.GetObject("PUSH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings_file_version=1
        ///gRadiosityEmissiveSurfaceScale=8.000000
        ///gRadiosityFirstBounceScale=1.000000
        ///gRadiosityMultiBounceScale=1.000000
        ///gRadiosityAlbedoOverbrightAmount=0.1
        ///gRadiosityAlbedoSaturationAmount=1.000000
        ///gRadiositySpecularGlossScale=0.85
        ///gDeferredEmissiveSurfaceScale=1.487500
        ///gDeferredEmissiveSurfaceExponent=0.563500
        ///.
        /// </summary>
        internal static string RADIOSITY_SETTINGS {
            get {
                return ResourceManager.GetString("RADIOSITY_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RIOT_GUARD {
            get {
                object obj = ResourceManager.GetObject("RIOT_GUARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SECURITY_GUARD {
            get {
                object obj = ResourceManager.GetObject("SECURITY_GUARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SEEGSON_MAGAZINEMAN {
            get {
                object obj = ResourceManager.GetObject("SEEGSON_MAGAZINEMAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SHOTGUN_INCENDIARY {
            get {
                object obj = ResourceManager.GetObject("SHOTGUN_INCENDIARY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SHOTGUN_NORMAL {
            get {
                object obj = ResourceManager.GetObject("SHOTGUN_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SHOTGUN_NORMAL_NPC {
            get {
                object obj = ResourceManager.GetObject("SHOTGUN_NORMAL_NPC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SHOTGUN_SLUG {
            get {
                object obj = ResourceManager.GetObject("SHOTGUN_SLUG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOWLEVEL_B_W {
            get {
                object obj = ResourceManager.GetObject("SHOWLEVEL_B+W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOWLEVEL_EVAC {
            get {
                object obj = ResourceManager.GetObject("SHOWLEVEL_EVAC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SHOWLEVEL_EVAC1 {
            get {
                object obj = ResourceManager.GetObject("SHOWLEVEL_EVAC1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scattering_radius=1.500000
        ///scattering_saturation=2.000000
        ///.
        /// </summary>
        internal static string SKIN_SHADING_SETTINGS {
            get {
                return ResourceManager.GetString("SKIN_SHADING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SMG_DUM_DUM {
            get {
                object obj = ResourceManager.GetObject("SMG_DUM_DUM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SMG_NORMAL {
            get {
                object obj = ResourceManager.GetObject("SMG_NORMAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SPACESUIT_NPC {
            get {
                object obj = ResourceManager.GetObject("SPACESUIT_NPC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAYLOR {
            get {
                object obj = ResourceManager.GetObject("TAYLOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TAYLOR1 {
            get {
                object obj = ResourceManager.GetObject("TAYLOR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] THE_PLAYER {
            get {
                object obj = ResourceManager.GetObject("THE_PLAYER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TRANSIT_STATION {
            get {
                object obj = ResourceManager.GetObject("TRANSIT_STATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_ANDROID {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_ANDROID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_HUMAN {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_HUMAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_HUMAN_HEIGHTENED {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_HUMAN_HEIGHTENED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_NONE {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_NONE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_SLEEPING {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_SLEEPING", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESET_STANDARD {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESET_STANDARD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VIEWCONESETS {
            get {
                object obj = ResourceManager.GetObject("VIEWCONESETS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WeifenLuo_WinFormsUI_Docking {
            get {
                object obj = ResourceManager.GetObject("WeifenLuo_WinFormsUI_Docking", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
