//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LegendPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAbortMeleeAttack.
        /// </summary>
        internal static string ActionAbortMeleeAttack {
            get {
                return ResourceManager.GetString("ActionAbortMeleeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffectedByFlameThrower.
        /// </summary>
        internal static string ActionAffectedByFlameThrower {
            get {
                return ResourceManager.GetString("ActionAffectedByFlameThrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAffectedByFlameThrowerInVent.
        /// </summary>
        internal static string ActionAffectedByFlameThrowerInVent {
            get {
                return ResourceManager.GetString("ActionAffectedByFlameThrowerInVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAlienWonScareTest.
        /// </summary>
        internal static string ActionAlienWonScareTest {
            get {
                return ResourceManager.GetString("ActionAlienWonScareTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionApplyPrimaryDamageControlResponse.
        /// </summary>
        internal static string ActionApplyPrimaryDamageControlResponse {
            get {
                return ResourceManager.GetString("ActionApplyPrimaryDamageControlResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionAssert.
        /// </summary>
        internal static string ActionAssert {
            get {
                return ResourceManager.GetString("ActionAssert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionBackstageAlienResponse.
        /// </summary>
        internal static string ActionBackstageAlienResponse {
            get {
                return ResourceManager.GetString("ActionBackstageAlienResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionBackstageAreaSweep.
        /// </summary>
        internal static string ActionBackstageAreaSweep {
            get {
                return ResourceManager.GetString("ActionBackstageAreaSweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionBreakout.
        /// </summary>
        internal static string ActionBreakout {
            get {
                return ResourceManager.GetString("ActionBreakout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionBrokenCover.
        /// </summary>
        internal static string ActionBrokenCover {
            get {
                return ResourceManager.GetString("ActionBrokenCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionChangeCover.
        /// </summary>
        internal static string ActionChangeCover {
            get {
                return ResourceManager.GetString("ActionChangeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDead.
        /// </summary>
        internal static string ActionDead {
            get {
                return ResourceManager.GetString("ActionDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDebugMenuLinkItem.
        /// </summary>
        internal static string ActionDebugMenuLinkItem {
            get {
                return ResourceManager.GetString("ActionDebugMenuLinkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDebugString.
        /// </summary>
        internal static string ActionDebugString {
            get {
                return ResourceManager.GetString("ActionDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDespawn.
        /// </summary>
        internal static string ActionDespawn {
            get {
                return ResourceManager.GetString("ActionDespawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionDoneSystematicSearch.
        /// </summary>
        internal static string ActionDoneSystematicSearch {
            get {
                return ResourceManager.GetString("ActionDoneSystematicSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionExpireTimer.
        /// </summary>
        internal static string ActionExpireTimer {
            get {
                return ResourceManager.GetString("ActionExpireTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionFail.
        /// </summary>
        internal static string ActionFail {
            get {
                return ResourceManager.GetString("ActionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionFakeSense.
        /// </summary>
        internal static string ActionFakeSense {
            get {
                return ResourceManager.GetString("ActionFakeSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionForceIdle.
        /// </summary>
        internal static string ActionForceIdle {
            get {
                return ResourceManager.GetString("ActionForceIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionForceSearch.
        /// </summary>
        internal static string ActionForceSearch {
            get {
                return ResourceManager.GetString("ActionForceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionGetOutOfTheWay.
        /// </summary>
        internal static string ActionGetOutOfTheWay {
            get {
                return ResourceManager.GetString("ActionGetOutOfTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionHitTargetAndRun.
        /// </summary>
        internal static string ActionHitTargetAndRun {
            get {
                return ResourceManager.GetString("ActionHitTargetAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdle.
        /// </summary>
        internal static string ActionIdle {
            get {
                return ResourceManager.GetString("ActionIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleInCover.
        /// </summary>
        internal static string ActionIdleInCover {
            get {
                return ResourceManager.GetString("ActionIdleInCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTime.
        /// </summary>
        internal static string ActionIdleTime {
            get {
                return ResourceManager.GetString("ActionIdleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTimeFacingSuspiciousItem.
        /// </summary>
        internal static string ActionIdleTimeFacingSuspiciousItem {
            get {
                return ResourceManager.GetString("ActionIdleTimeFacingSuspiciousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTimeFacingTarget.
        /// </summary>
        internal static string ActionIdleTimeFacingTarget {
            get {
                return ResourceManager.GetString("ActionIdleTimeFacingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTimeFacingTargetMostRecentSensedPosition.
        /// </summary>
        internal static string ActionIdleTimeFacingTargetMostRecentSensedPosition {
            get {
                return ResourceManager.GetString("ActionIdleTimeFacingTargetMostRecentSensedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTimeFacingTargetOutsideCombatArea.
        /// </summary>
        internal static string ActionIdleTimeFacingTargetOutsideCombatArea {
            get {
                return ResourceManager.GetString("ActionIdleTimeFacingTargetOutsideCombatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionIdleTimeFacingTargetSensedPosition.
        /// </summary>
        internal static string ActionIdleTimeFacingTargetSensedPosition {
            get {
                return ResourceManager.GetString("ActionIdleTimeFacingTargetSensedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionListeningInConvo.
        /// </summary>
        internal static string ActionListeningInConvo {
            get {
                return ResourceManager.GetString("ActionListeningInConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMakeAggressive.
        /// </summary>
        internal static string ActionMakeAggressive {
            get {
                return ResourceManager.GetString("ActionMakeAggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMeleeAttack.
        /// </summary>
        internal static string ActionMeleeAttack {
            get {
                return ResourceManager.GetString("ActionMeleeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveInDirection.
        /// </summary>
        internal static string ActionMoveInDirection {
            get {
                return ResourceManager.GetString("ActionMoveInDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveThroughTarget.
        /// </summary>
        internal static string ActionMoveThroughTarget {
            get {
                return ResourceManager.GetString("ActionMoveThroughTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToAttackTarget.
        /// </summary>
        internal static string ActionMoveToAttackTarget {
            get {
                return ResourceManager.GetString("ActionMoveToAttackTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToBackstageViaVentClosestToAlien.
        /// </summary>
        internal static string ActionMoveToBackstageViaVentClosestToAlien {
            get {
                return ResourceManager.GetString("ActionMoveToBackstageViaVentClosestToAlien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToConvo.
        /// </summary>
        internal static string ActionMoveToConvo {
            get {
                return ResourceManager.GetString("ActionMoveToConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToCover.
        /// </summary>
        internal static string ActionMoveToCover {
            get {
                return ResourceManager.GetString("ActionMoveToCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToFrontStageViaFlankedVentClosestToPlayer.
        /// </summary>
        internal static string ActionMoveToFrontStageViaFlankedVentClosestToPlayer {
            get {
                return ResourceManager.GetString("ActionMoveToFrontStageViaFlankedVentClosestToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToMostRecentSensedPosition.
        /// </summary>
        internal static string ActionMoveToMostRecentSensedPosition {
            get {
                return ResourceManager.GetString("ActionMoveToMostRecentSensedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToNearestStandingPointToTarget.
        /// </summary>
        internal static string ActionMoveToNearestStandingPointToTarget {
            get {
                return ResourceManager.GetString("ActionMoveToNearestStandingPointToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToObjective.
        /// </summary>
        internal static string ActionMoveToObjective {
            get {
                return ResourceManager.GetString("ActionMoveToObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveToTarget.
        /// </summary>
        internal static string ActionMoveToTarget {
            get {
                return ResourceManager.GetString("ActionMoveToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionMoveWithGamepad.
        /// </summary>
        internal static string ActionMoveWithGamepad {
            get {
                return ResourceManager.GetString("ActionMoveWithGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionNotifySquad.
        /// </summary>
        internal static string ActionNotifySquad {
            get {
                return ResourceManager.GetString("ActionNotifySquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPauseSenses.
        /// </summary>
        internal static string ActionPauseSenses {
            get {
                return ResourceManager.GetString("ActionPauseSenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPerformAmbush.
        /// </summary>
        internal static string ActionPerformAmbush {
            get {
                return ResourceManager.GetString("ActionPerformAmbush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPerformRole.
        /// </summary>
        internal static string ActionPerformRole {
            get {
                return ResourceManager.GetString("ActionPerformRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPlayerController.
        /// </summary>
        internal static string ActionPlayerController {
            get {
                return ResourceManager.GetString("ActionPlayerController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPlayTree.
        /// </summary>
        internal static string ActionPlayTree {
            get {
                return ResourceManager.GetString("ActionPlayTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionPlayTreeAndFaceTarget.
        /// </summary>
        internal static string ActionPlayTreeAndFaceTarget {
            get {
                return ResourceManager.GetString("ActionPlayTreeAndFaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionRangedAim.
        /// </summary>
        internal static string ActionRangedAim {
            get {
                return ResourceManager.GetString("ActionRangedAim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionRangedShoot.
        /// </summary>
        internal static string ActionRangedShoot {
            get {
                return ResourceManager.GetString("ActionRangedShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionRequestCover.
        /// </summary>
        internal static string ActionRequestCover {
            get {
                return ResourceManager.GetString("ActionRequestCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionResetSearchJobs.
        /// </summary>
        internal static string ActionResetSearchJobs {
            get {
                return ResourceManager.GetString("ActionResetSearchJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionScript.
        /// </summary>
        internal static string ActionScript {
            get {
                return ResourceManager.GetString("ActionScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSetFrameFlag.
        /// </summary>
        internal static string ActionSetFrameFlag {
            get {
                return ResourceManager.GetString("ActionSetFrameFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSetGaugeAmount.
        /// </summary>
        internal static string ActionSetGaugeAmount {
            get {
                return ResourceManager.GetString("ActionSetGaugeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSetLogicCharacterFlags.
        /// </summary>
        internal static string ActionSetLogicCharacterFlags {
            get {
                return ResourceManager.GetString("ActionSetLogicCharacterFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSetMenaceManager.
        /// </summary>
        internal static string ActionSetMenaceManager {
            get {
                return ResourceManager.GetString("ActionSetMenaceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSetWithdrawState.
        /// </summary>
        internal static string ActionSetWithdrawState {
            get {
                return ResourceManager.GetString("ActionSetWithdrawState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSpeakingInConvo.
        /// </summary>
        internal static string ActionSpeakingInConvo {
            get {
                return ResourceManager.GetString("ActionSpeakingInConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionStartTimer.
        /// </summary>
        internal static string ActionStartTimer {
            get {
                return ResourceManager.GetString("ActionStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionStartTimerRandom.
        /// </summary>
        internal static string ActionStartTimerRandom {
            get {
                return ResourceManager.GetString("ActionStartTimerRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuccess.
        /// </summary>
        internal static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuspectTargetResponse.
        /// </summary>
        internal static string ActionSuspectTargetResponse {
            get {
                return ResourceManager.GetString("ActionSuspectTargetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuspend.
        /// </summary>
        internal static string ActionSuspend {
            get {
                return ResourceManager.GetString("ActionSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuspiciousItemDoneStage.
        /// </summary>
        internal static string ActionSuspiciousItemDoneStage {
            get {
                return ResourceManager.GetString("ActionSuspiciousItemDoneStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuspiciousItemMoveTo.
        /// </summary>
        internal static string ActionSuspiciousItemMoveTo {
            get {
                return ResourceManager.GetString("ActionSuspiciousItemMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSuspiciousItemReaction.
        /// </summary>
        internal static string ActionSuspiciousItemReaction {
            get {
                return ResourceManager.GetString("ActionSuspiciousItemReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionSwitchToNextTarget.
        /// </summary>
        internal static string ActionSwitchToNextTarget {
            get {
                return ResourceManager.GetString("ActionSwitchToNextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionTakeStep.
        /// </summary>
        internal static string ActionTakeStep {
            get {
                return ResourceManager.GetString("ActionTakeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionThreatAware.
        /// </summary>
        internal static string ActionThreatAware {
            get {
                return ResourceManager.GetString("ActionThreatAware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionThreatEscalation.
        /// </summary>
        internal static string ActionThreatEscalation {
            get {
                return ResourceManager.GetString("ActionThreatEscalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionTriggerSound.
        /// </summary>
        internal static string ActionTriggerSound {
            get {
                return ResourceManager.GetString("ActionTriggerSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionWeaponEquip.
        /// </summary>
        internal static string ActionWeaponEquip {
            get {
                return ResourceManager.GetString("ActionWeaponEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAlienIsAllowed.
        /// </summary>
        internal static string ConditionAlienIsAllowed {
            get {
                return ResourceManager.GetString("ConditionAlienIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAllowedToAttackTarget.
        /// </summary>
        internal static string ConditionAllowedToAttackTarget {
            get {
                return ResourceManager.GetString("ConditionAllowedToAttackTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAllowedToDoSuspiciousWarning.
        /// </summary>
        internal static string ConditionAllowedToDoSuspiciousWarning {
            get {
                return ResourceManager.GetString("ConditionAllowedToDoSuspiciousWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAllowedToPursueTarget.
        /// </summary>
        internal static string ConditionAllowedToPursueTarget {
            get {
                return ResourceManager.GetString("ConditionAllowedToPursueTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAllowedToSearch.
        /// </summary>
        internal static string ConditionAllowedToSearch {
            get {
                return ResourceManager.GetString("ConditionAllowedToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAngleFromTargetAgainstTargetCameraDirnLessThan.
        /// </summary>
        internal static string ConditionAngleFromTargetAgainstTargetCameraDirnLessThan {
            get {
                return ResourceManager.GetString("ConditionAngleFromTargetAgainstTargetCameraDirnLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAngleNPCToTargetsAimLessThan.
        /// </summary>
        internal static string ConditionAngleNPCToTargetsAimLessThan {
            get {
                return ResourceManager.GetString("ConditionAngleNPCToTargetsAimLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAngleToTargetLessThan.
        /// </summary>
        internal static string ConditionAngleToTargetLessThan {
            get {
                return ResourceManager.GetString("ConditionAngleToTargetLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionAnotherAlienIsAttackingThisTarget.
        /// </summary>
        internal static string ConditionAnotherAlienIsAttackingThisTarget {
            get {
                return ResourceManager.GetString("ConditionAnotherAlienIsAttackingThisTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCanBeControlledByGamepad.
        /// </summary>
        internal static string ConditionCanBeControlledByGamepad {
            get {
                return ResourceManager.GetString("ConditionCanBeControlledByGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCanBreakout.
        /// </summary>
        internal static string ConditionCanBreakout {
            get {
                return ResourceManager.GetString("ConditionCanBreakout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCanShootNow.
        /// </summary>
        internal static string ConditionCanShootNow {
            get {
                return ResourceManager.GetString("ConditionCanShootNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCanTakeStep.
        /// </summary>
        internal static string ConditionCanTakeStep {
            get {
                return ResourceManager.GetString("ConditionCanTakeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCheckHealthState.
        /// </summary>
        internal static string ConditionCheckHealthState {
            get {
                return ResourceManager.GetString("ConditionCheckHealthState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionConvoInteruppted.
        /// </summary>
        internal static string ConditionConvoInteruppted {
            get {
                return ResourceManager.GetString("ConditionConvoInteruppted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionConvoInterupptedByPlayer.
        /// </summary>
        internal static string ConditionConvoInterupptedByPlayer {
            get {
                return ResourceManager.GetString("ConditionConvoInterupptedByPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCurrentWeaponIsEquipped.
        /// </summary>
        internal static string ConditionCurrentWeaponIsEquipped {
            get {
                return ResourceManager.GetString("ConditionCurrentWeaponIsEquipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionCurrentWeaponNeedsReloading.
        /// </summary>
        internal static string ConditionCurrentWeaponNeedsReloading {
            get {
                return ResourceManager.GetString("ConditionCurrentWeaponNeedsReloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionDebugMenuLinkTest.
        /// </summary>
        internal static string ConditionDebugMenuLinkTest {
            get {
                return ResourceManager.GetString("ConditionDebugMenuLinkTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionEventAOccuredAfterB.
        /// </summary>
        internal static string ConditionEventAOccuredAfterB {
            get {
                return ResourceManager.GetString("ConditionEventAOccuredAfterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionGameIsDifficulty.
        /// </summary>
        internal static string ConditionGameIsDifficulty {
            get {
                return ResourceManager.GetString("ConditionGameIsDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAggroLevel.
        /// </summary>
        internal static string ConditionHasAggroLevel {
            get {
                return ResourceManager.GetString("ConditionHasAggroLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAlertnessState.
        /// </summary>
        internal static string ConditionHasAlertnessState {
            get {
                return ResourceManager.GetString("ConditionHasAlertnessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAmbushPoint.
        /// </summary>
        internal static string ConditionHasAmbushPoint {
            get {
                return ResourceManager.GetString("ConditionHasAmbushPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAnySenseBeenAbove.
        /// </summary>
        internal static string ConditionHasAnySenseBeenAbove {
            get {
                return ResourceManager.GetString("ConditionHasAnySenseBeenAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAnySenseBeenAboveWithinTime.
        /// </summary>
        internal static string ConditionHasAnySenseBeenAboveWithinTime {
            get {
                return ResourceManager.GetString("ConditionHasAnySenseBeenAboveWithinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasAWeapon.
        /// </summary>
        internal static string ConditionHasAWeapon {
            get {
                return ResourceManager.GetString("ConditionHasAWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasDoneSuspectResponseMoveTo.
        /// </summary>
        internal static string ConditionHasDoneSuspectResponseMoveTo {
            get {
                return ResourceManager.GetString("ConditionHasDoneSuspectResponseMoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasDoneSuspectResponseWithinTime.
        /// </summary>
        internal static string ConditionHasDoneSuspectResponseWithinTime {
            get {
                return ResourceManager.GetString("ConditionHasDoneSuspectResponseWithinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasFlankedVentCloseToPlayer.
        /// </summary>
        internal static string ConditionHasFlankedVentCloseToPlayer {
            get {
                return ResourceManager.GetString("ConditionHasFlankedVentCloseToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasGroupAwarenessState.
        /// </summary>
        internal static string ConditionHasGroupAwarenessState {
            get {
                return ResourceManager.GetString("ConditionHasGroupAwarenessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasKilltrap.
        /// </summary>
        internal static string ConditionHasKilltrap {
            get {
                return ResourceManager.GetString("ConditionHasKilltrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasMeleeAttackAvailable.
        /// </summary>
        internal static string ConditionHasMeleeAttackAvailable {
            get {
                return ResourceManager.GetString("ConditionHasMeleeAttackAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasMeleeAttackAvailableOrIsAttacking.
        /// </summary>
        internal static string ConditionHasMeleeAttackAvailableOrIsAttacking {
            get {
                return ResourceManager.GetString("ConditionHasMeleeAttackAvailableOrIsAttacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasMeleeBlockAvailable.
        /// </summary>
        internal static string ConditionHasMeleeBlockAvailable {
            get {
                return ResourceManager.GetString("ConditionHasMeleeBlockAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasMeleeCounterAttackAvailable.
        /// </summary>
        internal static string ConditionHasMeleeCounterAttackAvailable {
            get {
                return ResourceManager.GetString("ConditionHasMeleeCounterAttackAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasMotivation.
        /// </summary>
        internal static string ConditionHasMotivation {
            get {
                return ResourceManager.GetString("ConditionHasMotivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasObjective.
        /// </summary>
        internal static string ConditionHasObjective {
            get {
                return ResourceManager.GetString("ConditionHasObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasScript.
        /// </summary>
        internal static string ConditionHasScript {
            get {
                return ResourceManager.GetString("ConditionHasScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasSearchedMostRecentSensedPosition.
        /// </summary>
        internal static string ConditionHasSearchedMostRecentSensedPosition {
            get {
                return ResourceManager.GetString("ConditionHasSearchedMostRecentSensedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasSenseActivationBeenAbove.
        /// </summary>
        internal static string ConditionHasSenseActivationBeenAbove {
            get {
                return ResourceManager.GetString("ConditionHasSenseActivationBeenAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasTimerExpired.
        /// </summary>
        internal static string ConditionHasTimerExpired {
            get {
                return ResourceManager.GetString("ConditionHasTimerExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasToken.
        /// </summary>
        internal static string ConditionHasToken {
            get {
                return ResourceManager.GetString("ConditionHasToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasValidCoverToChangeTo.
        /// </summary>
        internal static string ConditionHasValidCoverToChangeTo {
            get {
                return ResourceManager.GetString("ConditionHasValidCoverToChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasValidRouteToNearTarget.
        /// </summary>
        internal static string ConditionHasValidRouteToNearTarget {
            get {
                return ResourceManager.GetString("ConditionHasValidRouteToNearTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasValidRouteToTarget.
        /// </summary>
        internal static string ConditionHasValidRouteToTarget {
            get {
                return ResourceManager.GetString("ConditionHasValidRouteToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHasVentCloseToAlien.
        /// </summary>
        internal static string ConditionHasVentCloseToAlien {
            get {
                return ResourceManager.GetString("ConditionHasVentCloseToAlien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHaveNextTarget.
        /// </summary>
        internal static string ConditionHaveNextTarget {
            get {
                return ResourceManager.GetString("ConditionHaveNextTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionHaveTarget.
        /// </summary>
        internal static string ConditionHaveTarget {
            get {
                return ResourceManager.GetString("ConditionHaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionInConvo.
        /// </summary>
        internal static string ConditionInConvo {
            get {
                return ResourceManager.GetString("ConditionInConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionInPositionForConvo.
        /// </summary>
        internal static string ConditionInPositionForConvo {
            get {
                return ResourceManager.GetString("ConditionInPositionForConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsAnySenseActivationAbove.
        /// </summary>
        internal static string ConditionIsAnySenseActivationAbove {
            get {
                return ResourceManager.GetString("ConditionIsAnySenseActivationAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsBackstage.
        /// </summary>
        internal static string ConditionIsBackstage {
            get {
                return ResourceManager.GetString("ConditionIsBackstage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsBranchActive.
        /// </summary>
        internal static string ConditionIsBranchActive {
            get {
                return ResourceManager.GetString("ConditionIsBranchActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCharacterClass.
        /// </summary>
        internal static string ConditionIsCharacterClass {
            get {
                return ResourceManager.GetString("ConditionIsCharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCorpseTrap.
        /// </summary>
        internal static string ConditionIsCorpseTrap {
            get {
                return ResourceManager.GetString("ConditionIsCorpseTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCoverExposed.
        /// </summary>
        internal static string ConditionIsCoverExposed {
            get {
                return ResourceManager.GetString("ConditionIsCoverExposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCoverTooClose.
        /// </summary>
        internal static string ConditionIsCoverTooClose {
            get {
                return ResourceManager.GetString("ConditionIsCoverTooClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCrouching.
        /// </summary>
        internal static string ConditionIsCrouching {
            get {
                return ResourceManager.GetString("ConditionIsCrouching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsCurrentCoverValid.
        /// </summary>
        internal static string ConditionIsCurrentCoverValid {
            get {
                return ResourceManager.GetString("ConditionIsCurrentCoverValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsDead.
        /// </summary>
        internal static string ConditionIsDead {
            get {
                return ResourceManager.GetString("ConditionIsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsEnemyOfTarget.
        /// </summary>
        internal static string ConditionIsEnemyOfTarget {
            get {
                return ResourceManager.GetString("ConditionIsEnemyOfTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsFrameFlagSet.
        /// </summary>
        internal static string ConditionIsFrameFlagSet {
            get {
                return ResourceManager.GetString("ConditionIsFrameFlagSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsGaugeAmountAbove.
        /// </summary>
        internal static string ConditionIsGaugeAmountAbove {
            get {
                return ResourceManager.GetString("ConditionIsGaugeAmountAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsGaugeAmountBelow.
        /// </summary>
        internal static string ConditionIsGaugeAmountBelow {
            get {
                return ResourceManager.GetString("ConditionIsGaugeAmountBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsInCombatArea.
        /// </summary>
        internal static string ConditionIsInCombatArea {
            get {
                return ResourceManager.GetString("ConditionIsInCombatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsInCover.
        /// </summary>
        internal static string ConditionIsInCover {
            get {
                return ResourceManager.GetString("ConditionIsInCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsInCrawlSpace.
        /// </summary>
        internal static string ConditionIsInCrawlSpace {
            get {
                return ResourceManager.GetString("ConditionIsInCrawlSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsInTargetsWeaponRange.
        /// </summary>
        internal static string ConditionIsInTargetsWeaponRange {
            get {
                return ResourceManager.GetString("ConditionIsInTargetsWeaponRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsInVent.
        /// </summary>
        internal static string ConditionIsInVent {
            get {
                return ResourceManager.GetString("ConditionIsInVent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsPartOfNPCGroup.
        /// </summary>
        internal static string ConditionIsPartOfNPCGroup {
            get {
                return ResourceManager.GetString("ConditionIsPartOfNPCGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsPerformingRoleOrCouldPerformRole.
        /// </summary>
        internal static string ConditionIsPerformingRoleOrCouldPerformRole {
            get {
                return ResourceManager.GetString("ConditionIsPerformingRoleOrCouldPerformRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsRequestingCover.
        /// </summary>
        internal static string ConditionIsRequestingCover {
            get {
                return ResourceManager.GetString("ConditionIsRequestingCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsSenseActivationAbove.
        /// </summary>
        internal static string ConditionIsSenseActivationAbove {
            get {
                return ResourceManager.GetString("ConditionIsSenseActivationAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionIsTargetInDeepCrouch.
        /// </summary>
        internal static string ConditionIsTargetInDeepCrouch {
            get {
                return ResourceManager.GetString("ConditionIsTargetInDeepCrouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeSearchedWithinTime.
        /// </summary>
        internal static string ConditionLastTimeSearchedWithinTime {
            get {
                return ResourceManager.GetString("ConditionLastTimeSearchedWithinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeSensed.
        /// </summary>
        internal static string ConditionLastTimeSensed {
            get {
                return ResourceManager.GetString("ConditionLastTimeSensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeSensedFloat.
        /// </summary>
        internal static string ConditionLastTimeSensedFloat {
            get {
                return ResourceManager.GetString("ConditionLastTimeSensedFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeSquadNotified.
        /// </summary>
        internal static string ConditionLastTimeSquadNotified {
            get {
                return ResourceManager.GetString("ConditionLastTimeSquadNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeTargetShotAtMe.
        /// </summary>
        internal static string ConditionLastTimeTargetShotAtMe {
            get {
                return ResourceManager.GetString("ConditionLastTimeTargetShotAtMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLastTimeWasAbleToShootTarget.
        /// </summary>
        internal static string ConditionLastTimeWasAbleToShootTarget {
            get {
                return ResourceManager.GetString("ConditionLastTimeWasAbleToShootTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionListeningInConvo.
        /// </summary>
        internal static string ConditionListeningInConvo {
            get {
                return ResourceManager.GetString("ConditionListeningInConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionLogicCharacterFlags.
        /// </summary>
        internal static string ConditionLogicCharacterFlags {
            get {
                return ResourceManager.GetString("ConditionLogicCharacterFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionMostRecentSenseActivationHasBeenAbove.
        /// </summary>
        internal static string ConditionMostRecentSenseActivationHasBeenAbove {
            get {
                return ResourceManager.GetString("ConditionMostRecentSenseActivationHasBeenAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionNeedsToGetOutOfTheWay.
        /// </summary>
        internal static string ConditionNeedsToGetOutOfTheWay {
            get {
                return ResourceManager.GetString("ConditionNeedsToGetOutOfTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionObjectiveIsInCombatArea.
        /// </summary>
        internal static string ConditionObjectiveIsInCombatArea {
            get {
                return ResourceManager.GetString("ConditionObjectiveIsInCombatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionObjectiveIsWithinDistance.
        /// </summary>
        internal static string ConditionObjectiveIsWithinDistance {
            get {
                return ResourceManager.GetString("ConditionObjectiveIsWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionPlayerIsAnEnemy.
        /// </summary>
        internal static string ConditionPlayerIsAnEnemy {
            get {
                return ResourceManager.GetString("ConditionPlayerIsAnEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionPlayerIsInExploitableArea.
        /// </summary>
        internal static string ConditionPlayerIsInExploitableArea {
            get {
                return ResourceManager.GetString("ConditionPlayerIsInExploitableArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionPlayerJoinedConvo.
        /// </summary>
        internal static string ConditionPlayerJoinedConvo {
            get {
                return ResourceManager.GetString("ConditionPlayerJoinedConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionRangeTestForScriptedWithdrawal.
        /// </summary>
        internal static string ConditionRangeTestForScriptedWithdrawal {
            get {
                return ResourceManager.GetString("ConditionRangeTestForScriptedWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionRequiresPrimaryDamageControlResponse.
        /// </summary>
        internal static string ConditionRequiresPrimaryDamageControlResponse {
            get {
                return ResourceManager.GetString("ConditionRequiresPrimaryDamageControlResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionScriptedWithdrawRequested.
        /// </summary>
        internal static string ConditionScriptedWithdrawRequested {
            get {
                return ResourceManager.GetString("ConditionScriptedWithdrawRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionShouldFollow.
        /// </summary>
        internal static string ConditionShouldFollow {
            get {
                return ResourceManager.GetString("ConditionShouldFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionShouldProcessSuspiciousItem.
        /// </summary>
        internal static string ConditionShouldProcessSuspiciousItem {
            get {
                return ResourceManager.GetString("ConditionShouldProcessSuspiciousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionShouldSuspend.
        /// </summary>
        internal static string ConditionShouldSuspend {
            get {
                return ResourceManager.GetString("ConditionShouldSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionShouldUseCover.
        /// </summary>
        internal static string ConditionShouldUseCover {
            get {
                return ResourceManager.GetString("ConditionShouldUseCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSomeoneJoinedConvo.
        /// </summary>
        internal static string ConditionSomeoneJoinedConvo {
            get {
                return ResourceManager.GetString("ConditionSomeoneJoinedConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSquadDoingEscalation.
        /// </summary>
        internal static string ConditionSquadDoingEscalation {
            get {
                return ResourceManager.GetString("ConditionSquadDoingEscalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSquadDoingSuspiciousWarning.
        /// </summary>
        internal static string ConditionSquadDoingSuspiciousWarning {
            get {
                return ResourceManager.GetString("ConditionSquadDoingSuspiciousWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemBTPriority.
        /// </summary>
        internal static string ConditionSuspiciousItemBTPriority {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemBTPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemFirstGroupMember.
        /// </summary>
        internal static string ConditionSuspiciousItemFirstGroupMember {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemFirstGroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemGroupAllowedToProgress.
        /// </summary>
        internal static string ConditionSuspiciousItemGroupAllowedToProgress {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemGroupAllowedToProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemGroupMembersRoutingTo.
        /// </summary>
        internal static string ConditionSuspiciousItemGroupMembersRoutingTo {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemGroupMembersRoutingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemIsWithinDistance.
        /// </summary>
        internal static string ConditionSuspiciousItemIsWithinDistance {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemIsWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemShouldDoStage.
        /// </summary>
        internal static string ConditionSuspiciousItemShouldDoStage {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemShouldDoStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionSuspiciousItemWaitForGroupRouting.
        /// </summary>
        internal static string ConditionSuspiciousItemWaitForGroupRouting {
            get {
                return ResourceManager.GetString("ConditionSuspiciousItemWaitForGroupRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTalkingInConvo.
        /// </summary>
        internal static string ConditionTalkingInConvo {
            get {
                return ResourceManager.GetString("ConditionTalkingInConvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsInCombatArea.
        /// </summary>
        internal static string ConditionTargetIsInCombatArea {
            get {
                return ResourceManager.GetString("ConditionTargetIsInCombatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsInWeaponRange.
        /// </summary>
        internal static string ConditionTargetIsInWeaponRange {
            get {
                return ResourceManager.GetString("ConditionTargetIsInWeaponRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsOnlyAccessibleCrouching.
        /// </summary>
        internal static string ConditionTargetIsOnlyAccessibleCrouching {
            get {
                return ResourceManager.GetString("ConditionTargetIsOnlyAccessibleCrouching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsPlayer.
        /// </summary>
        internal static string ConditionTargetIsPlayer {
            get {
                return ResourceManager.GetString("ConditionTargetIsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsTargetingMe.
        /// </summary>
        internal static string ConditionTargetIsTargetingMe {
            get {
                return ResourceManager.GetString("ConditionTargetIsTargetingMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsUsingMeleeAttack.
        /// </summary>
        internal static string ConditionTargetIsUsingMeleeAttack {
            get {
                return ResourceManager.GetString("ConditionTargetIsUsingMeleeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinAggroRadius.
        /// </summary>
        internal static string ConditionTargetIsWithinAggroRadius {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinAggroRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinDistance.
        /// </summary>
        internal static string ConditionTargetIsWithinDistance {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinDistanceOfAlien.
        /// </summary>
        internal static string ConditionTargetIsWithinDistanceOfAlien {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinDistanceOfAlien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinDistanceThreshold.
        /// </summary>
        internal static string ConditionTargetIsWithinDistanceThreshold {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinDistanceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinDistanceUnobscured.
        /// </summary>
        internal static string ConditionTargetIsWithinDistanceUnobscured {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinDistanceUnobscured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetIsWithinRoutingDistance.
        /// </summary>
        internal static string ConditionTargetIsWithinRoutingDistance {
            get {
                return ResourceManager.GetString("ConditionTargetIsWithinRoutingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetLogicCharacterFlags.
        /// </summary>
        internal static string ConditionTargetLogicCharacterFlags {
            get {
                return ResourceManager.GetString("ConditionTargetLogicCharacterFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetNearestStandPointIsWithinDistance.
        /// </summary>
        internal static string ConditionTargetNearestStandPointIsWithinDistance {
            get {
                return ResourceManager.GetString("ConditionTargetNearestStandPointIsWithinDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetsWeaponHasAmmo.
        /// </summary>
        internal static string ConditionTargetsWeaponHasAmmo {
            get {
                return ResourceManager.GetString("ConditionTargetsWeaponHasAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionTargetsWeaponHasProperty.
        /// </summary>
        internal static string ConditionTargetsWeaponHasProperty {
            get {
                return ResourceManager.GetString("ConditionTargetsWeaponHasProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionVisualSomeRaysThroughGlass.
        /// </summary>
        internal static string ConditionVisualSomeRaysThroughGlass {
            get {
                return ResourceManager.GetString("ConditionVisualSomeRaysThroughGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionWasSenseThresholdLastIncreaseActivation.
        /// </summary>
        internal static string ConditionWasSenseThresholdLastIncreaseActivation {
            get {
                return ResourceManager.GetString("ConditionWasSenseThresholdLastIncreaseActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionWasSenseThresholdLastIncreaseActivationAbove.
        /// </summary>
        internal static string ConditionWasSenseThresholdLastIncreaseActivationAbove {
            get {
                return ResourceManager.GetString("ConditionWasSenseThresholdLastIncreaseActivationAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionWithdrawState.
        /// </summary>
        internal static string ConditionWithdrawState {
            get {
                return ResourceManager.GetString("ConditionWithdrawState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorAggressionEscalation.
        /// </summary>
        internal static string DecoratorAggressionEscalation {
            get {
                return ResourceManager.GetString("DecoratorAggressionEscalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorAwarenessState.
        /// </summary>
        internal static string DecoratorAwarenessState {
            get {
                return ResourceManager.GetString("DecoratorAwarenessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorBranch.
        /// </summary>
        internal static string DecoratorBranch {
            get {
                return ResourceManager.GetString("DecoratorBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorLockBestVents.
        /// </summary>
        internal static string DecoratorLockBestVents {
            get {
                return ResourceManager.GetString("DecoratorLockBestVents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorLoop.
        /// </summary>
        internal static string DecoratorLoop {
            get {
                return ResourceManager.GetString("DecoratorLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorMood.
        /// </summary>
        internal static string DecoratorMood {
            get {
                return ResourceManager.GetString("DecoratorMood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorPercentage.
        /// </summary>
        internal static string DecoratorPercentage {
            get {
                return ResourceManager.GetString("DecoratorPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorSetSenseSet.
        /// </summary>
        internal static string DecoratorSetSenseSet {
            get {
                return ResourceManager.GetString("DecoratorSetSenseSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorSquadSearch.
        /// </summary>
        internal static string DecoratorSquadSearch {
            get {
                return ResourceManager.GetString("DecoratorSquadSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorSuspiciousItemInProgress.
        /// </summary>
        internal static string DecoratorSuspiciousItemInProgress {
            get {
                return ResourceManager.GetString("DecoratorSuspiciousItemInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecoratorTimer.
        /// </summary>
        internal static string DecoratorTimer {
            get {
                return ResourceManager.GetString("DecoratorTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultBehaviour.
        /// </summary>
        internal static string DefaultBehaviour {
            get {
                return ResourceManager.GetString("DefaultBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In_Game_Menu_Text.
        /// </summary>
        internal static string In_Game_Menu_Text {
            get {
                return ResourceManager.GetString("In_Game_Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeGroupActions.
        /// </summary>
        internal static string NodeGroupActions {
            get {
                return ResourceManager.GetString("NodeGroupActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeGroupConditions.
        /// </summary>
        internal static string NodeGroupConditions {
            get {
                return ResourceManager.GetString("NodeGroupConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeGroupDecorators.
        /// </summary>
        internal static string NodeGroupDecorators {
            get {
                return ResourceManager.GetString("NodeGroupDecorators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeGroupSelectors.
        /// </summary>
        internal static string NodeGroupSelectors {
            get {
                return ResourceManager.GetString("NodeGroupSelectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeGroupSequences.
        /// </summary>
        internal static string NodeGroupSequences {
            get {
                return ResourceManager.GetString("NodeGroupSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestShutDownSpeed.
        /// </summary>
        internal static string RequestShutDownSpeed {
            get {
                return ResourceManager.GetString("RequestShutDownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorLinear.
        /// </summary>
        internal static string SelectorLinear {
            get {
                return ResourceManager.GetString("SelectorLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorPercentage.
        /// </summary>
        internal static string SelectorPercentage {
            get {
                return ResourceManager.GetString("SelectorPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceLinear.
        /// </summary>
        internal static string SequenceLinear {
            get {
                return ResourceManager.GetString("SequenceLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceStateless.
        /// </summary>
        internal static string SequenceStateless {
            get {
                return ResourceManager.GetString("SequenceStateless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimerType.
        /// </summary>
        internal static string TimerType {
            get {
                return ResourceManager.GetString("TimerType", resourceCulture);
            }
        }
    }
}
