//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainiac.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brainiac.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node represents the current behavior..
        /// </summary>
        internal static string BehaviorDesc {
            get {
                return ResourceManager.GetString("BehaviorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string BehaviorFilename {
            get {
                return ResourceManager.GetString("BehaviorFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file which holds this behaviour..
        /// </summary>
        internal static string BehaviorFilenameDesc {
            get {
                return ResourceManager.GetString("BehaviorFilenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior is empty..
        /// </summary>
        internal static string BehaviorIsEmptyError {
            get {
                return ResourceManager.GetString("BehaviorIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string CategoryBasic {
            get {
                return ResourceManager.GetString("CategoryBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CategoryComment {
            get {
                return ResourceManager.GetString("CategoryComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string CategoryDesign {
            get {
                return ResourceManager.GetString("CategoryDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string ConditionConnectorsFalse {
            get {
                return ResourceManager.GetString("ConditionConnectorsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string ConditionConnectorsTrue {
            get {
                return ResourceManager.GetString("ConditionConnectorsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator has no child..
        /// </summary>
        internal static string DecoratorHasNoChildError {
            get {
                return ResourceManager.GetString("DecoratorHasNoChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Definition.
        /// </summary>
        internal static string EditorAIDefinition {
            get {
                return ResourceManager.GetString("EditorAIDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string EditorRandom {
            get {
                return ResourceManager.GetString("EditorRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Value.
        /// </summary>
        internal static string EditorRandomValue {
            get {
                return ResourceManager.GetString("EditorRandomValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string EditorValue {
            get {
                return ResourceManager.GetString("EditorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Event.
        /// </summary>
        internal static string EventBlockEvent {
            get {
                return ResourceManager.GetString("EventBlockEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true the event is blocked..
        /// </summary>
        internal static string EventBlockEventDesc {
            get {
                return ResourceManager.GetString("EventBlockEventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both styles may not be null..
        /// </summary>
        internal static string ExceptionBothStylesNull {
            get {
                return ResourceManager.GetString("ExceptionBothStylesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default style may not be null..
        /// </summary>
        internal static string ExceptionDefaultStyleNull {
            get {
                return ResourceManager.GetString("ExceptionDefaultStyleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse value {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumCouldNotParseValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumCouldNotParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read value {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumCouldNotReadValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumCouldNotReadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum index found {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumIllegalEnumIndex {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumIllegalEnumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value {0} is illegal.
        /// </summary>
        internal static string ExceptionDesignerAttributeEnumValueIllegal {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeEnumValueIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum expected {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeExpectedEnum {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeExpectedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal boolean value {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalBooleanValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal float value {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalFloatValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalFloatValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal integer value {0}.
        /// </summary>
        internal static string ExceptionDesignerAttributeIllegalIntegerValue {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeIllegalIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type.
        /// </summary>
        internal static string ExceptionDesignerAttributeInvalidType {
            get {
                return ResourceManager.GetString("ExceptionDesignerAttributeInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicated connector identifier was found. The identifier must be unique over the whole solution!.
        /// </summary>
        internal static string ExceptionDuplicatedConnectorIdentifier {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedConnectorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing attribute &quot;{0}&quot;.
        /// </summary>
        internal static string ExceptionFileManagerXMLMissingAttribute {
            get {
                return ResourceManager.GetString("ExceptionFileManagerXMLMissingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such editor {0}..
        /// </summary>
        internal static string ExceptionFlexiblePropertyInvalidEditor {
            get {
                return ResourceManager.GetString("ExceptionFlexiblePropertyInvalidEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be read {0}..
        /// </summary>
        internal static string ExceptionFlexiblePropertyInvalidValue {
            get {
                return ResourceManager.GetString("ExceptionFlexiblePropertyInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a definition may not contain any spaces..
        /// </summary>
        internal static string ExceptionInvalidDefinitionName {
            get {
                return ResourceManager.GetString("ExceptionInvalidDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create event of type {0}. Constructor may only require the node it is created for as a parameter..
        /// </summary>
        internal static string ExceptionMissingEventConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingEventConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create node of type {0}. Constructor may not require any parameters..
        /// </summary>
        internal static string ExceptionMissingNodeConstructor {
            get {
                return ResourceManager.GetString("ExceptionMissingNodeConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can only be one BehaviorManagerInterface..
        /// </summary>
        internal static string ExceptionMultipleBehaviorManagerInterfaces {
            get {
                return ResourceManager.GetString("ExceptionMultipleBehaviorManagerInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one loadable or savable attribute is allowed..
        /// </summary>
        internal static string ExceptionMultipleDesignerAttributes {
            get {
                return ResourceManager.GetString("ExceptionMultipleDesignerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node is not allowed to have more children..
        /// </summary>
        internal static string ExceptionNodeHasTooManyChildren {
            get {
                return ResourceManager.GetString("ExceptionNodeHasTooManyChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is not a child of this node..
        /// </summary>
        internal static string ExceptionNodeIsNoChild {
            get {
                return ResourceManager.GetString("ExceptionNodeIsNoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subitem for the connector could be found..
        /// </summary>
        internal static string ExceptionNoSubItemForConnector {
            get {
                return ResourceManager.GetString("ExceptionNoSubItemForConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given type does not implement the DefaultObject interface..
        /// </summary>
        internal static string ExceptionNotImplementDefaultObject {
            get {
                return ResourceManager.GetString("ExceptionNotImplementDefaultObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All designer properties must be readable..
        /// </summary>
        internal static string ExceptionPropertyCannotBeRead {
            get {
                return ResourceManager.GetString("ExceptionPropertyCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All designer properties must be writable or flagged as read only and no save..
        /// </summary>
        internal static string ExceptionPropertyCannotBeWritten {
            get {
                return ResourceManager.GetString("ExceptionPropertyCannotBeWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subitem does not belong to this node..
        /// </summary>
        internal static string ExceptionSubItemIsNoChild {
            get {
                return ResourceManager.GetString("ExceptionSubItemIsNoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given color is not handled..
        /// </summary>
        internal static string ExceptionUnhandledCommentColor {
            get {
                return ResourceManager.GetString("ExceptionUnhandledCommentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled node shape..
        /// </summary>
        internal static string ExceptionUnhandledNodeShape {
            get {
                return ResourceManager.GetString("ExceptionUnhandledNodeShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such event type {0}..
        /// </summary>
        internal static string ExceptionUnknownEventType {
            get {
                return ResourceManager.GetString("ExceptionUnknownEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such node type {0}..
        /// </summary>
        internal static string ExceptionUnknownNodeType {
            get {
                return ResourceManager.GetString("ExceptionUnknownNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given node tag type cannot be used with the given type..
        /// </summary>
        internal static string ExceptionWrongNodeTagType {
            get {
                return ResourceManager.GetString("ExceptionWrongNodeTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string ImpulseDelay {
            get {
                return ResourceManager.GetString("ImpulseDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time which must have passed before the node can become active again..
        /// </summary>
        internal static string ImpulseDelayDesc {
            get {
                return ResourceManager.GetString("ImpulseDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string ImpulseDuration {
            get {
                return ResourceManager.GetString("ImpulseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how old the oldest event may be for this node to become valid..
        /// </summary>
        internal static string ImpulseDurationDesc {
            get {
                return ResourceManager.GetString("ImpulseDurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string NodeCommentBackground {
            get {
                return ResourceManager.GetString("NodeCommentBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background color rendered behind the node and its children..
        /// </summary>
        internal static string NodeCommentBackgroundDesc {
            get {
                return ResourceManager.GetString("NodeCommentBackgroundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string NodeCommentText {
            get {
                return ResourceManager.GetString("NodeCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment shown for the node and its children..
        /// </summary>
        internal static string NodeCommentTextDesc {
            get {
                return ResourceManager.GetString("NodeCommentTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel has no children..
        /// </summary>
        internal static string ParallelNoChildrenError {
            get {
                return ResourceManager.GetString("ParallelNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel has only one child and could be removed..
        /// </summary>
        internal static string ParallelOnlyOneChildError {
            get {
                return ResourceManager.GetString("ParallelOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found circular reference..
        /// </summary>
        internal static string ReferencedBehaviorCircularReferenceError {
            get {
                return ResourceManager.GetString("ReferencedBehaviorCircularReferenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node works like an action which calls the referenced behavior..
        /// </summary>
        internal static string ReferencedBehaviorDesc {
            get {
                return ResourceManager.GetString("ReferencedBehaviorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string ReferencedBehaviorFilename {
            get {
                return ResourceManager.GetString("ReferencedBehaviorFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file loaded as the referenced behaviour..
        /// </summary>
        internal static string ReferencedBehaviorFilenameDesc {
            get {
                return ResourceManager.GetString("ReferencedBehaviorFilenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector has no children..
        /// </summary>
        internal static string SelectorNoChildrenError {
            get {
                return ResourceManager.GetString("SelectorNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector has only one child and could be removed..
        /// </summary>
        internal static string SelectorOnlyOneChildError {
            get {
                return ResourceManager.GetString("SelectorOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence has no children..
        /// </summary>
        internal static string SequenceNoChildrenError {
            get {
                return ResourceManager.GetString("SequenceNoChildrenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence has only one child and could be removed..
        /// </summary>
        internal static string SequenceOnlyOneChildError {
            get {
                return ResourceManager.GetString("SequenceOnlyOneChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string UnitsSeconds {
            get {
                return ResourceManager.GetString("UnitsSeconds", resourceCulture);
            }
        }
    }
}
